# Generated by Django 4.2 on 2023-05-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_nuevomodelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NuevoModelo',
        ),
    ]
