# Generated by Django 4.2 on 2023-08-03 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_personal_puesto_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='id_hotel',
            field=models.ForeignKey(blank=True, db_column='id_hotel', null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.hotel'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad',
            field=models.SmallIntegerField(default=0),
        ),
    ]
