# Generated by Django 5.0 on 2024-01-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_personal_id_hotel_reserva_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('resenaId', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Resena',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicioId', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.PositiveBigIntegerField()),
                ('servicio_tipo', models.CharField(blank=True, max_length=500, null=True)),
                ('detalle', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Servicio',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='habitacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': False},
        ),
    ]
