# Generated by Django 5.0 on 2024-02-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_resena_servicio_alter_ciudad_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='id_departamento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_ciudad',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='id_ciudad',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='id_ciudad',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='id_hotel',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_habitacion',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='id_hotel',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_personal',
        ),
        migrations.DeleteModel(
            name='Resena',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='departamento',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
