# Generated by Django 4.2 on 2024-02-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_servicio_habitacion_foto_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
