# Generated by Django 4.2 on 2024-02-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_personal_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
