# Generated by Django 4.2 on 2024-02-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0008_cliente_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resena',
            name='resenaId',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='servicioId',
        ),
        migrations.AddField(
            model_name='resena',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
