# Generated by Django 4.2 on 2024-02-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0009_remove_resena_resenaid_remove_servicio_servicioid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='servicio_tipo',
            new_name='tipo',
        ),
    ]
