# Generated by Django 4.2 on 2024-02-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_rename_servicio_tipo_servicio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='id_personal',
            field=models.ForeignKey(blank=True, db_column='id_personal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.personal'),
        ),
    ]
